---
- hosts: webserver
  become: yes
  tasks:  
  - name: install git
    apt:
     name: "{{mywebserverpackforubuntu}}"
     state: present
  - name: install web-server
    apt:
     name: "{{mywebserverpackforubuntu}}"
     state: absent